# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:12:18+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

from models import (
    BuyRecommendationResponse,
    KeywordSearchResponse,
    ProductDetailsResponse,
    SortOptionResponse,
)

app = MCPProxy(
    contact={'email': 'support@axesso.de'},
    description='Use this api to fetch information to Amazon products and more.',
    license={
        'name': 'Apache 2.0',
        'url': 'http://www.apache.org/licenses/LICENSE-2.0.html',
    },
    title='Axesso Api',
    version='1.0.0',
    servers=[{'url': 'http://api.axesso.de'}],
)


@app.get(
    '/amz/amazon-lookup-buy-recommendations',
    tags=['product_recommendations', 'product_lookup'],
)
def request_buy_recommendation(url: str):
    """
    request buy recommendations to a given product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/amz/amazon-lookup-product', tags=['product_lookup'])
def request_product(url: str, size: Optional[str] = None):
    """
    lookup product information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/amz/amazon-search-by-keyword',
    tags=['keyword_based_search', 'product_lookup', 'search_result_sorting'],
)
def keyword_search(
    keyword: str,
    domain_code: str = Query(..., alias='domainCode'),
    sort_by: Optional[str] = Query('relevanceblender', alias='sortBy'),
    number_of_products: Optional[int] = Query('20', alias='numberOfProducts'),
):
    """
    fetch results auf a keyword search on Amazon
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/amz/sort-options', tags=['keyword_based_search', 'search_result_sorting'])
def sort_options():
    """
    request available sort options to use in keyword search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
