# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T16:12:18+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class BuyRecommendationResponse(BaseModel):
    buyRecommendations: Optional[List[str]] = None
    numberOfProducts: Optional[int] = None
    responseMessage: Optional[str] = Field(
        None, examples=['Product successfully found!']
    )
    responseStatus: Optional[str] = Field(None, examples=['PRODUCT_FOUND_RESPONSE'])


class KeywordSearchResponse(BaseModel):
    domainCode: Optional[str] = Field(None, examples=['com'])
    foundProducts: Optional[List[str]] = None
    keyword: Optional[str] = Field(None, examples=['Playstation 4'])
    numberOfProducts: Optional[int] = None
    responseMessage: Optional[str] = Field(
        None, examples=['Product successfully found!']
    )
    responseStatus: Optional[str] = Field(None, examples=['PRODUCT_FOUND_RESPONSE'])
    sortStrategy: Optional[str] = Field(None, examples=['date-desc-rank'])


class ProductDetailsResponse(BaseModel):
    answeredQuestions: Optional[int] = None
    asin: Optional[str] = Field(None, examples=['B077Q3YRP5'])
    countReview: Optional[int] = None
    features: Optional[List[str]] = None
    fulfilledBy: Optional[str] = Field(None, examples=['Amazon'])
    manufacturer: Optional[str] = Field(None, examples=['Sony'])
    price: Optional[float] = None
    priceSaving: Optional[str] = Field(None, examples=['You Save: $59,58 (43%)'])
    priceShippingInformation: Optional[str] = Field(None, examples=['free'])
    prime: Optional[bool] = None
    productRating: Optional[str] = Field(None, examples=['4.4 out of 5 stars'])
    productTitle: Optional[str] = Field(None, examples=['Playstation 4'])
    responseMessage: Optional[str] = Field(
        None, examples=['Product successfully found!']
    )
    responseStatus: Optional[str] = Field(None, examples=['PRODUCT_FOUND_RESPONSE'])
    retailPrice: Optional[float] = None
    sizeSelection: Optional[List[str]] = None
    soldBy: Optional[str] = Field(None, examples=['Sony'])
    warehouseAvailability: Optional[str] = Field(None, examples=['In Stock'])


class SortOption(BaseModel):
    order: Optional[int] = None
    sortName: Optional[str] = Field(None, examples=['relevanceblender'])
    strategy: Optional[str] = Field(None, examples=['AMAZON_FEATURED'])


class SortOptionResponse(BaseModel):
    responseMessage: Optional[str] = Field(
        None, examples=['Product successfully found!']
    )
    responseStatus: Optional[str] = Field(None, examples=['PRODUCT_FOUND_RESPONSE'])
    resultSize: Optional[int] = None
    sortOptions: Optional[List[SortOption]] = None
